import * as T from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {createHouse} from './model.js';import {lighting} from './lighting.js';import {ui} from './ui.js';import {P} from './parameters.js';
const viewport=document.querySelector('#viewport');try{
 const scene=new T.Scene();scene.background=new T.Color(0xe6e9e7);const renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;viewport.append(renderer.domElement);
 const camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.1,150);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=120;controls.maxPolarAngle=Math.PI*.49;controls.target.set(5,2.7,4);const groups=createHouse(scene);const mode=lighting(scene,groups.ground,groups.first);
 function reset(view='whole'){const y=view==='first'?P.groundElevation+P.floorHeight+1:view==='ground'?1:2.7;controls.target.set(5,y,4);const d=Math.max(1,1.15/camera.aspect);camera.position.set(5+19*d,y+17*d,4+24*d);controls.update()}
 function top(view){const y=view==='first'?P.groundElevation+P.floorHeight:0;controls.target.set(5,y,4);camera.position.set(5,y+(Math.max(30,31/camera.aspect)),4+.01);controls.update()}
 const resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)};addEventListener('resize',resize);resize();reset();ui(groups,reset,mode,top);mode(false);
 let frames=0;renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);if(++frames===3)window.houseReady=true});window.house={scene,camera,renderer,controls,groups};
}catch(e){document.querySelector('#status').textContent='WebGL unavailable';viewport.innerHTML='<p style="margin:200px 25px">Enable WebGL / hardware acceleration or try Chrome, Edge or Safari.</p>';console.error(e)}
